name: Update EC2 via SSM

on:
  workflow_dispatch:
    inputs:
      instance-id:
        description: "EC2 Instance ID to update"
        required: true
jobs:
  update-ec2:
    runs-on: [self-hosted, test]

    steps:
      - name: Send SSM Command to EC2
        run: |
          aws ssm send-command \
            --instance-ids ${{ github.event.inputs.instance-id }} \
            --document-name "AWS-RunPatchBaseline" \
            --comment "Update system" \
            --parameters '{"Operation":["Install"]}' \
            --timeout-seconds 600 \
            --query "Command.CommandId" \
            --output text
