# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
    inputs:
      InstanceID:
        description: "EC2 Instance ID to update"
        required: true
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: us-west-2

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      # with:
      #   python-version: "3.9"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install boto3
    - name: Run python script
      run: python3 python/patching-python.py
      env:
        InstanceID: ${{ github.event.inputs.InstanceID }}
        region: us-west-2
