name: Patching-python

on:
  workflow_dispatch:
    inputs:
      instance-id:
        description: "EC2 Instance ID to update"
        required: true
jobs:
  update-ec2:
   runs-on: ubuntu-latest  # Use GitHub-hosted runner


   steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Change to your region

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"   # Choose your Python version
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run python script
        run: python patching-python.py "${{ github.event.inputs.instance-id }}"
