name: Patch

on:
  workflow_dispatch:
    inputs:
      instance-id:
        description: "EC2 Instance ID to update"
        required: true
jobs:
  update-ec2:
   runs-on: ubuntu-latest  # Use GitHub-hosted runner


   steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Change to your region

      - name: Make shell script executable
        run: chmod +x patch_without_reboot.sh

      - name: Run shell script
        run: ./patching.sh "${{ github.event.inputs.instance-ids }}"
