name: Update EC2 via SSM

on:
  workflow_run:
    workflows: ["Update EC2"]  # Must exactly match the name in workflow-1.yml
    types:
      - completed

jobs:
  job-2:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Change to your region

      - name: Make shell script executable
        run: chmod +x stop_services.sh

      - name: Run shell script
        run: ./stop_services.sh "${{ github.event.inputs.instance-ids }}"
