name: Update EC2 via SSM

on:
  workflow_dispatch:

jobs:
  update-ec2:
   runs-on: ubuntu-latest  # Use GitHub-hosted runner


   steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make shell script executable
        run: chmod +x patch_without_reboot.sh

      - name: Run shell script
        run: ./patch_without_reboot.sh
